#!/bin/bash
set -e
echo $METABASE_PULLS
for N in `echo $METABASE_PULLS`; do
  echo "Applying pull request $N https://github.com/metabase/metabase/pull/$N"
  PURL="https://patch-diff.githubusercontent.com/raw/metabase/metabase/pull/$N.patch"
  curl -L -o pull-$N.patch $PURL
  patch -p1 < pull-$N.patch
done
